name: Build and Release Signed APK

on:
  push:
    branches: [ "devel" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Build Tools
        run: sdkmanager "build-tools;35.0.0"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > app/release.keystore

      - name: Build Release APK (Unsigned)
        run: ./gradlew assembleRelease

      - name: Sign Android APK
        run: |
          BUILD_TOOLS_PATH=$(ls -d $ANDROID_SDK_ROOT/build-tools/* | sort -V | tail -1)
          echo "Menggunakan Build Tools dari: $BUILD_TOOLS_PATH"

          $BUILD_TOOLS_PATH/zipalign -v 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/app-release-final.apk

          $BUILD_TOOLS_PATH/apksigner sign \
            --ks app/release.keystore \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --ks-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" \
            --out app/build/outputs/apk/release/app-signed.apk \
            app/build/outputs/apk/release/app-release.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: app/build/outputs/apk/release/app-signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
